apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - image: nicolaka/netshoot
      name: netshoot
      command: ["sleep", "infinity"]
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: