# Loadbalancers are nodeport based
# They use the nodeport to get the functionality

apiVersion: v1
kind: Service
metadata:
 name: kubia-loadbalancer
spec:
 type: LoadBalancer 
 ports:
 - port: 80
   targetPort: 8080
 selector:
    app: kubia