apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-example
spec:
  # running the job at 0 15 30 45 minutes of every hour, every day
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: peridoic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: nicolaka/netshoot:latest
            command: ["sleep", "10"]
