# Nodeport is not used as it is, never. But it is used as a foundation
# for all other better networking options to work
# Fundamentally all it does is open a port on all of the nodes of the cluster
# the traffic coming into the port will get intercepted by kubeproxy and 
# redirected to the object you specified in the manifest

# 1. It uses ugly ports 30000-32767
# 2. Client needs to know an IP address which would be constant and fixed.
# That is not the case with the nodeport, if a node gets evicted your client
# breaks if it depends on the IP it had.
# 3. Simple security, we are punching holes into our firewall, on EVERY single
# node in our cluster. Ridicilous if you ask me.

# Why does it exist then?
# A. It is a building block of load balancers, the way they work is via NodePort
# it's just that loadbalancers are created outside of the cluster.

apiVersion: v1
kind: Service
metadata:
  name: nodeport-example
  labels:
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: distributed-playground
spec:
  # The Strategy: Open a static port on every Node's WAN interface
  type: NodePort
  ports:
  # 1. port (INTERNAL VIRTUAL PORT)
  # This is the port *other pods* in the cluster use to talk to this Service.
  # Example: Another pod would call http://nodeport-example:8080
  - port: 8080
    
    # 2. targetPort (CONTAINER PORT)
    # This is the port your application code is actually listening on.
    # If your Go/Node/Python app listens on 8080, this MUST be 8080.
    targetPort: 8080
    
    # 3. nodePort (EXTERNAL PHYSICAL PORT)
    # This is the port exposed on the physical server/VM.
    # External users visit http://<Node-IP>:30080
    # Range is restricted to 30000-32767 by default.
    nodePort: 30080
    
  # The Link: This service sends traffic to any pod labeled "app: nodeapp"
  selector:
    app: nodeapp