apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app.kubernetes.io/name: fortune
    app.kubernetes.io/component: pod
    app.kubernetes.io/part-of: distributed-playground
spec:
  containers:
    # Container 1: The Content Creator (Writes data)
    - image: luksa/fortune
      name: html-generator
      volumeMounts:
        - name: html
          mountPath: /var/htdocs # Writer path
      resource: # Just a placeholder for the linter

    # Container 2: The Web Server (Reads data)
    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html # Reader path (Nginx default)
          readOnly: true # Security: Nginx cannot modify files
      ports:
        - containerPort: 80
          protocol: TCP
      resource: # Just a placeholder for the linter

  # The Shared Volume Definition
  volumes:
    - name: html
      emptyDir: {} # Default: stored on node's disk
      # emptyDir:                         # Alternative: stored in RAM (faster)
      #   medium: Memory
