apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: pod
    app.kubernetes.io/part-of: distributed-playground
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    resource: # Just a placeholder for the linter
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc  # References the claim, NOT the volume