apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain  # Data survives if claim is deleted
  gcePersistentDisk:                     # The specific hardcoded infrastructure
    pdName: mongodb
    fsType: ext4