apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 1Gi      # Must match or be smaller than the PV
  accessModes:
  - ReadWriteOnce       # Must match what the PV supports
  storageClassName: ""  # Disables dynamic provisioning (looks for manual PV)