apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    resource: # Just a placeholder for the linter
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc  # References the claim, NOT the volume