apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    app.kubernetes.io/name: kubia
    app.kubernetes.io/part-of: distributed-playground
spec:
  containers:
    - image: nicolaka/netshoot
      name: netshoot
      command: ["sleep", "infinity"]
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: