apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-labels
  labels:
    creation_method: manual
    prod: dev
spec:
  containers:
  - image: nicolaka/netshoot
    name: netshoot
    command: ["sleep", "infinity"]
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
    # place holder for the resources